/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 08-Nov-2016 11:54:14 PM 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Inventory.conversions_Inventory.ingredient_measurements]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Inventory.conversions] DROP CONSTRAINT [FK_Inventory.conversions_Inventory.ingredient_measurements]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Inventory.conversions_Inventory.measurementunits]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Inventory.conversions] DROP CONSTRAINT [FK_Inventory.conversions_Inventory.measurementunits]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Inventory.ingredient_measurements_Inventory.measurementunits]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Inventory.ingredient_measurements] DROP CONSTRAINT [FK_Inventory.ingredient_measurements_Inventory.measurementunits]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Inventory.ingredient_measurements_Inventory.stock]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Inventory.ingredient_measurements] DROP CONSTRAINT [FK_Inventory.ingredient_measurements_Inventory.stock]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_movements_movementconpects]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Inventory.movements] DROP CONSTRAINT [FK_movements_movementconpects]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_movements_stock]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Inventory.movements] DROP CONSTRAINT [FK_movements_stock]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_movements_warehouses]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Inventory.movements] DROP CONSTRAINT [FK_movements_warehouses]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_stock_ingredients]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Inventory.stock] DROP CONSTRAINT [FK_stock_ingredients]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_stock_warehouses]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Inventory.stock] DROP CONSTRAINT [FK_stock_warehouses]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_dish_ingredients_dishes]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Kitchen.dish_ingredients] DROP CONSTRAINT [FK_dish_ingredients_dishes]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_dish_ingredients_ingredients]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Kitchen.dish_ingredients] DROP CONSTRAINT [FK_dish_ingredients_ingredients]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_order_dishes_dishes]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Sales.order_dishes] DROP CONSTRAINT [FK_order_dishes_dishes]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_order_dishes_orders]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Sales.order_dishes] DROP CONSTRAINT [FK_order_dishes_orders]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_orders_employees]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Sales.orders] DROP CONSTRAINT [FK_orders_employees]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_orders_orderstatus]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Sales.orders] DROP CONSTRAINT [FK_orders_orderstatus]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[HumanResource.employees]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [HumanResource.employees]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Inventory.conversions]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Inventory.conversions]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Inventory.ingredient_measurements]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Inventory.ingredient_measurements]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Inventory.measurementunits]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Inventory.measurementunits]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Inventory.movementconcepts]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Inventory.movementconcepts]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Inventory.movements]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Inventory.movements]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Inventory.stock]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Inventory.stock]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Inventory.warehouses]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Inventory.warehouses]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Kitchen.dish_ingredients]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Kitchen.dish_ingredients]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Kitchen.dishes]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Kitchen.dishes]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Kitchen.ingredients]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Kitchen.ingredients]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Sales.order_dishes]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Sales.order_dishes]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Sales.orders]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Sales.orders]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Sales.orderstatus]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Sales.orderstatus]
GO

/* Create Tables */

CREATE TABLE [HumanResource.employees]
(
	[emp_id] smallint NOT NULL,
	[emp_name] varchar(70) NOT NULL,
	[emp_lastname] varchar(70) NOT NULL,
	[emp_type] char(5) NOT NULL,
	[emp_nickname] varchar(50) NOT NULL,
	[emp_passwd] varchar(50) NOT NULL
)
GO

CREATE TABLE [Inventory.conversions]
(
	[cvn_id] int NOT NULL IDENTITY (1, 1),
	[cvn_from_id_ing_measurement] int NOT NULL,
	[cvn_to] char(3) NOT NULL,
	[cvn_factor] int NOT NULL,
	[ims_id] int NULL
)
GO

CREATE TABLE [Inventory.ingredient_measurements]
(
	[ims_id] int NOT NULL IDENTITY (1, 1),
	[ims_id_ingredient] int NOT NULL,
	[ims_id_measurement] char(3) NOT NULL
)
GO

CREATE TABLE [Inventory.measurementunits]
(
	[meu_id] char(3) NOT NULL,
	[meu_description] varchar(50) NOT NULL
)
GO

CREATE TABLE [Inventory.movementconcepts]
(
	[mco_id] int NOT NULL,
	[mco_description] varchar(50) NOT NULL
)
GO

CREATE TABLE [Inventory.movements]
(
	[mov_id] int NOT NULL IDENTITY (1, 1),
	[mov_date] datetime NOT NULL,
	[mov_quantity] int NOT NULL,
	[mov_id_warehouse] int NOT NULL,
	[mov_id_stock_ingredient] int NOT NULL,
	[mov_concept] int NOT NULL
)
GO

CREATE TABLE [Inventory.stock]
(
	[sto_id_ing] int NOT NULL,
	[war_id] int NOT NULL,
	[sto_quantity] int NOT NULL,
	[sto_min] int NULL,
	[sto_max] int NOT NULL
)
GO

CREATE TABLE [Inventory.warehouses]
(
	[war_id] int NOT NULL,
	[war_name] varchar(50) NOT NULL
)
GO

CREATE TABLE [Kitchen.dish_ingredients]
(
	[ing_id] int NOT NULL,
	[dis_id] int NOT NULL,
	[dis_ing_quantity] int NOT NULL
)
GO

CREATE TABLE [Kitchen.dishes]
(
	[dis_id] int NOT NULL,
	[dis_name] varchar(50) NOT NULL,
	[dis_description] text NOT NULL,
	[dis_price] money NOT NULL
)
GO

CREATE TABLE [Kitchen.ingredients]
(
	[ing_id] int NOT NULL,
	[ing_description] varchar(50) NOT NULL
)
GO

CREATE TABLE [Sales.order_dishes]
(
	[dis_id] int NOT NULL,
	[ord_id] int NOT NULL,
	[ord_dis_quantity] int NOT NULL,
	[ord_date] datetime NOT NULL,
	[ord_total] money NOT NULL
)
GO

CREATE TABLE [Sales.orders]
(
	[ord_id] int NOT NULL,
	[ord_date] datetime NOT NULL,
	[ord_subtotal] money NOT NULL,
	[ord_iva] money NOT NULL,
	[ord_total] money NOT NULL,
	[ord_status] int NOT NULL,
	[ord_employee_id] smallint NOT NULL
)
GO

CREATE TABLE [Sales.orderstatus]
(
	[ors_id] int NOT NULL,
	[ors_description] varchar(50) NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [HumanResource.employees] 
 ADD CONSTRAINT [PK_employees]
	PRIMARY KEY CLUSTERED ([emp_id] ASC)
GO

ALTER TABLE [Inventory.conversions] 
 ADD CONSTRAINT [PK_Inventory.conversions]
	PRIMARY KEY CLUSTERED ([cvn_id] ASC)
GO

ALTER TABLE [Inventory.conversions] 
 ADD CONSTRAINT [UN_ing_conversion] UNIQUE NONCLUSTERED ([cvn_from_id_ing_measurement] ASC,[cvn_to] ASC)
GO

ALTER TABLE [Inventory.ingredient_measurements] 
 ADD CONSTRAINT [PK_Inventory.ingredient_measurements]
	PRIMARY KEY CLUSTERED ([ims_id] ASC)
GO

ALTER TABLE [Inventory.ingredient_measurements] 
 ADD CONSTRAINT [UN_ing_meu] UNIQUE NONCLUSTERED ([ims_id_ingredient] ASC,[ims_id_measurement] ASC)
GO

ALTER TABLE [Inventory.measurementunits] 
 ADD CONSTRAINT [PK_measurementunits]
	PRIMARY KEY CLUSTERED ([meu_id] ASC)
GO

ALTER TABLE [Inventory.movementconcepts] 
 ADD CONSTRAINT [PK_movementconpects]
	PRIMARY KEY CLUSTERED ([mco_id] ASC)
GO

ALTER TABLE [Inventory.movements] 
 ADD CONSTRAINT [PK_movements]
	PRIMARY KEY CLUSTERED ([mov_id] ASC)
GO

ALTER TABLE [Inventory.stock] 
 ADD CONSTRAINT [PK_stock]
	PRIMARY KEY CLUSTERED ([sto_id_ing] ASC)
GO

ALTER TABLE [Inventory.warehouses] 
 ADD CONSTRAINT [PK_warehouses]
	PRIMARY KEY CLUSTERED ([war_id] ASC)
GO

ALTER TABLE [Kitchen.dish_ingredients] 
 ADD CONSTRAINT [PK_dish_ingredients]
	PRIMARY KEY CLUSTERED ([dis_id] ASC,[ing_id] ASC)
GO

ALTER TABLE [Kitchen.dishes] 
 ADD CONSTRAINT [PK_dishes]
	PRIMARY KEY CLUSTERED ([dis_id] ASC)
GO

ALTER TABLE [Kitchen.ingredients] 
 ADD CONSTRAINT [PK_ingredients]
	PRIMARY KEY CLUSTERED ([ing_id] ASC)
GO

ALTER TABLE [Sales.order_dishes] 
 ADD CONSTRAINT [PK_order_dishes]
	PRIMARY KEY CLUSTERED ([dis_id] ASC,[ord_id] ASC)
GO

ALTER TABLE [Sales.orders] 
 ADD CONSTRAINT [PK_orders]
	PRIMARY KEY CLUSTERED ([ord_id] ASC)
GO

ALTER TABLE [Sales.orderstatus] 
 ADD CONSTRAINT [PK_orderstatus]
	PRIMARY KEY CLUSTERED ([ors_id] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Inventory.conversions] ADD CONSTRAINT [FK_Inventory.conversions_Inventory.ingredient_measurements]
	FOREIGN KEY ([ims_id]) REFERENCES [Inventory.ingredient_measurements] ([ims_id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Inventory.conversions] ADD CONSTRAINT [FK_Inventory.conversions_Inventory.measurementunits]
	FOREIGN KEY ([cvn_to]) REFERENCES [Inventory.measurementunits] ([meu_id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Inventory.ingredient_measurements] ADD CONSTRAINT [FK_Inventory.ingredient_measurements_Inventory.measurementunits]
	FOREIGN KEY ([ims_id_measurement]) REFERENCES [Inventory.measurementunits] ([meu_id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Inventory.ingredient_measurements] ADD CONSTRAINT [FK_Inventory.ingredient_measurements_Inventory.stock]
	FOREIGN KEY ([ims_id_ingredient]) REFERENCES [Inventory.stock] ([sto_id_ing]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Inventory.movements] ADD CONSTRAINT [FK_movements_movementconpects]
	FOREIGN KEY ([mov_concept]) REFERENCES [Inventory.movementconcepts] ([mco_id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Inventory.movements] ADD CONSTRAINT [FK_movements_stock]
	FOREIGN KEY ([mov_id_stock_ingredient]) REFERENCES [Inventory.stock] ([sto_id_ing]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Inventory.movements] ADD CONSTRAINT [FK_movements_warehouses]
	FOREIGN KEY ([mov_id_warehouse]) REFERENCES  () ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Inventory.stock] ADD CONSTRAINT [FK_stock_ingredients]
	FOREIGN KEY ([sto_id_ing]) REFERENCES [Kitchen.ingredients] ([ing_id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Inventory.stock] ADD CONSTRAINT [FK_stock_warehouses]
	FOREIGN KEY ([war_id]) REFERENCES [Inventory.warehouses] ([war_id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Kitchen.dish_ingredients] ADD CONSTRAINT [FK_dish_ingredients_dishes]
	FOREIGN KEY ([dis_id]) REFERENCES [Kitchen.dishes] ([dis_id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Kitchen.dish_ingredients] ADD CONSTRAINT [FK_dish_ingredients_ingredients]
	FOREIGN KEY ([ing_id]) REFERENCES [Kitchen.ingredients] ([ing_id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Sales.order_dishes] ADD CONSTRAINT [FK_order_dishes_dishes]
	FOREIGN KEY ([dis_id]) REFERENCES [Kitchen.dishes] ([dis_id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Sales.order_dishes] ADD CONSTRAINT [FK_order_dishes_orders]
	FOREIGN KEY ([ord_id]) REFERENCES [Sales.orders] ([ord_id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Sales.orders] ADD CONSTRAINT [FK_orders_employees]
	FOREIGN KEY ([ord_employee_id]) REFERENCES [HumanResource.employees] ([emp_id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Sales.orders] ADD CONSTRAINT [FK_orders_orderstatus]
	FOREIGN KEY ([ord_status]) REFERENCES [Sales.orderstatus] ([ors_id]) ON DELETE No Action ON UPDATE No Action
GO
